environment:
  TARGET: x86_64-pc-windows-gnu
  MSYS2_BITS: 64
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-dll-win64-x64-3160200.zip'
  - cmd: 7z e sqlite-dll-win64-x64-3160200.zip -y > nul
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-amalgamation-3160200.zip'
  - cmd: 7z e sqlite-amalgamation-3160200.zip -y > nul
  - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER%
  - SET SQLITE3_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%

build: false

test_script:
  - cargo test --lib --verbose
  - cargo test --lib --verbose --features bundled
  - cargo test --lib --features "backup blob chrono functions limits load_extension serde_json trace"
  - cargo test --lib --features "backup blob chrono functions limits load_extension serde_json trace bundled"

cache:
  - C:\Users\appveyor\.cargo
