environment:
  TARGET: x86_64-pc-windows-msvc
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - curl -sSf -o sqlite-dll.zip http://sqlite.org/2016/sqlite-dll-win64-x64-3150100.zip
  - 7z e sqlite-dll.zip -y > nul
  - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER%

build: false

test_script:
  - cargo test --lib --verbose
  - cargo test --lib --features "backup blob chrono functions load_extension serde_json trace"

cache:
  - C:\Users\appveyor\.cargo
